name: Actions Test
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: issueID
        with: 
          token: ${{ secrets.GITHUB_TOKEN}}
          title: Title
          body: Body
          assignees: |
            vestemeansorin91
      - run: |
          echo ${{ steps.issue.outputs.issueID }}
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
